clustertypes = {
    "402": {
        "Neutrophils": [0, 1, 16, 24],
        "Neutrophil Progenitors": [5, 6, 26, 40],
        "Basophils": [15],
        "Macrophages": [2, 4, 29, 37],
        "Myeloid Progenitors": [14],
        "Monocyte Progenitors": [9, 17],
        "Monocytes": [3, 20],
        "cDC": [22],
        "pDC": [7, 36],
        "Multipotent Progenitors": [21],
        "Stromal Cells": [33],
        "T Cells": [8, 31, 32, 38],
        "NK Cells": [11],
        "B Cells": [18, 19, 25, 30, 35],
        "B Cell Progenitors": [10, 12, 28],
        "Plasma Cells": [23],
        "Unknown": [13, 41],
        "Megakaryocytes": [27, 39],
        "Erythroid Cells": [34]
    },
    "403": {
        "Neutrophils": [14, 15, 16, 33],
        "Neutrophil Progenitors": [3, 22],
        "Basophils": [10],
        "Macrophages": [4, 39, 40, 7, 28],
        "Myeloid Progenitors": [12, 19, 23],
        "Monocyte Progenitors": [26],
        "Monocytes": [6, 8],
        "cDC": [5],
        "pDC": [21, 35],
        "Multipotent Progenitors": [20],
        "Stromal Cells": [32],
        "T Cells": [1, 2, 11, 38],
        "NK Cells": [18],
        "B Cells": [0, 17, 24, 30],
        "B Cell Progenitors": [9, 13, 27, 29],
        "Plasma Cells": [36],
        "Unknown": [34],
        "Megakaryocytes": [31, 37],
        "Erythroid Cells": [25]
    },
    "404": {
        "Monocytes": [0, 2],
        "T cells": [1],
        "Neutrophils": [3, 14],
        "Myeloid Progenitors": [4],
        "Megakaryocytes": [5],
        "B Cell Progenitors": [6],
        "B Cells": [7],
        "Plasma Cells": [8],
        "Erythroid Cells": [9],
        "pDC": [10],
        "cDC": [11],
        "Macrophages": [12],
        "Basophils": [13]
    },
    "405": {
        "pDC": [0],
        "HSPCs": [1],
        "B Cells": [2],
        "B Cell Progenitors": [3],
        "T Cells": [4, 10],
        "Neutrophils": [5, 30],
        "Monocytes": [6, 9, 25],
        "Macrophages": [7, 27],
        "Monocyte Progenitors": [8],
        "cDC": [11],
        "Neutrophil Progenitors": [12],
        "Megakaryocytes": [13],
        "Stromal Cells": [14],
        "Erythroid Cells": [15],
        "Plasma Cells": [17],
        "Unknown": [
            16, 18, 19, 20, 21, 22, 23, 24, 26, 28, 29, 31, 32, 33, 34, 35,
            36, 37, 38, 39, 40, 41, 42
        ]
    }
}

markers = {
    "402": {
        "B Cell Progenitors": ["Ebf1", "Pax5", "Vpreb3", "Il7r", "Cd79a", "Sox4"],
        "B Cells": ["Ms4a1", "Cd79a", "Cd79b", "Igkc", "Ighm", "Cd74"],
        "Basophils": ["Mcpt8", "Cpa3", "Ms4a2", "Fcer1a", "Hdc"],
        "Erythroid Cells": ["Hba-a1", "Hbb-bs", "Car2", "Gypa", "Tfrc"],
        "Macrophages": ["Adgre1", "Csf1r", "Apoe", "Cd68", "Ctss"],
        "Megakaryocytes": ["Pf4", "Ppbp", "Itga2b", "Plek", "Fermt3"],
        "Monocyte Progenitors": ["Mki67", "Top2a", "Stmn1", "Crip1", "Fn1"],
        "Monocytes": ["Lyz2", "Ccr2", "S100a4", "S100a9", "Ctss"],
        "Multipotent Progenitors": ["Myb", "Flt3", "Cdk6", "Stmn1", "Rnf220"],
        "Myeloid Progenitors": ["H2afy", "Ptma", "Stmn1", "Rps12", "Rpl32"],
        "NK Cells": ["Ncr1", "Klrb1c", "Klrk1", "Nkg7", "Id2"],
        "Neutrophil Progenitors": ["Cebpe", "Camp", "Chil3", "S100a8", "Top2a"],
        "Neutrophils": ["Ly6g", "S100a9", "S100a8", "Lcn2", "Mmp9", "Itgam"],
        "Plasma Cells": ["Jchain", "Sdc1", "Mzb1", "Xbp1", "Ighm"],
        "Stromal Cells": ["Cxcl12", "Kitl", "Lepr", "Igfbp5", "Sparc", "Bgn"],
        "T Cells": ["Cd3d", "Cd3e", "Cd247", "Lck", "Trac"],
        "cDC": ["Cd74", "H2-Aa", "H2-Eb1", "Flt3", "Ciita"],
        "pDC": ["Siglech", "Tcf4", "Bst2", "Irf8", "Ly6d"]
    },
    "403": {
        "B Cell Progenitors": ["Ebf1", "Pax5", "Vpreb3", "Il7r", "Cd79a", "Sox4"],
        "B Cells": ["Ms4a1", "Cd79a", "Cd79b", "Igkc", "Ighm", "Cd74"],
        "Basophils": ["Mcpt8", "Cpa3", "Ms4a2", "Fcer1a", "Hdc"],
        "Erythroid Cells": ["Hba-a1", "Hbb-bs", "Car2", "Gypa", "Tfrc"],
        "Macrophages": ["Adgre1", "Csf1r", "Apoe", "Cd68", "Ctss"],
        "Megakaryocytes": ["Pf4", "Ppbp", "Itga2b", "Plek", "Fermt3"],
        "Monocyte Progenitors": ["Mki67", "Top2a", "Stmn1", "Crip1", "Fn1"],
        "Monocytes": ["Lyz2", "Ccr2", "S100a4", "S100a9", "Ctss"],
        "Multipotent Progenitors": ["Myb", "Flt3", "Cdk6", "Stmn1", "Rnf220"],
        "Myeloid Progenitors": ["H2afy", "Ptma", "Stmn1", "Rps12", "Rpl32"],
        "NK Cells": ["Ncr1", "Klrb1c", "Klrk1", "Nkg7", "Id2"],
        "Neutrophil Progenitors": ["Cebpe", "Camp", "Chil3", "S100a8", "Top2a"],
        "Neutrophils": ["Ly6g", "S100a9", "S100a8", "Lcn2", "Mmp9", "Itgam"],
        "Plasma Cells": ["Jchain", "Sdc1", "Mzb1", "Xbp1", "Ighm"],
        "Stromal Cells": ["Cxcl12", "Kitl", "Lepr", "Igfbp5", "Sparc", "Bgn"],
        "T Cells": ["Cd3d", "Cd3e", "Cd247", "Lck", "Trac"],
        "cDC": ["Cd74", "H2-Aa", "H2-Eb1", "Flt3", "Ciita"],
        "pDC": ["Siglech", "Tcf4", "Bst2", "Irf8", "Ly6d"]
    },
    "404": {
        'Monocytes': ['Ccr2', 'Ly6c2', 'Ifitm3', 'S100a4', 'Lst1'],
        'T Cells': ['Cd3d', 'Cd3e', 'Cd247', 'Lck', 'Trbc2'],
        'Neutrophils': ['Csf3r', 'Mmp9', 'Retnlg', 'Pglyrp1', 'Lcn2'],
        'Megakaryocytes': ['Pf4', 'Ppbp', 'Itgb3', 'Plek', 'Itga2b'],
        'B Cell Progenitors': ['Ebf1', 'Pax5', 'Vpreb3', 'Cd79a', 'Il7r'],
        'B Cells': ['Ms4a1', 'Pax5', 'Cd79a', 'Ebf1', 'H2-Aa'],
        'Plasma Cells': ['Jchain', 'Xbp1', 'Ighm', 'Pou2af1'],
        'Erythroid Cells': ['Hba-a1', 'Hbb-bs', 'Tfrc', 'Gypa', 'Slc4a1'],
        'pDC': ['Siglech', 'Tcf4', 'Bst2', 'Irf8', 'Irf7'],
        'cDC': ['Cd74', 'H2-Aa', 'Cst3', 'Ciita', 'Flt3'],
        'Macrophages': ['Adgre1', 'Itgam', 'Csf1r', 'C1qb', 'Apoe'],
        'Basophils': ['Prss34', 'Mcpt8', 'Cpa3', 'Fcer1a', 'Ms4a2'],
        'Myeloid Progenitors': ['H2afy', 'Ptma', 'Stmn1', 'Rps12', 'Rpl32'],
    },
    "405": {
        'pDC': ['Siglech', 'Tcf4', 'Irf8', 'Bst2', 'Runx2'],
        'HSPCs': ['Stmn1', 'Ptma', 'Cd34', 'Kit', 'Gata2'],
        'B Cells': ['Ms4a1', 'Cd79a', 'H2-Aa', 'Pax5', 'Bank1'],
        'B Cell Progenitors': ['Vpreb3', 'Pax5', 'Cd79a', 'Il7r'],
        'Neutrophils': ['Ly6g', 'Mmp9', 'Ltf', 'Pglyrp1', 'Chil3'],
        'Monocytes': ['Ly6c2', 'Ccr2', 'S100a4', 'Ifitm3', 'Csf1r'],
        'Macrophages': ['Adgre1', 'Csf1r', 'Apoe', 'C1qa', 'Mertk'],
        'T Cells': ['Cd3d', 'Cd3e', 'Cd247', 'Trbc2', 'Skap1'],
        'cDC': ['Zbtb46', 'H2-Aa', 'Flt3', 'Ciita', 'Cst3'],
        'Megakaryocytes': ['Ppbp', 'Itga2b', 'Itgb3', 'Plek', 'Pf4'],
        'Stromal Cells': ['Cxcl12', 'Lepr', 'Kitl', 'Igfbp5', 'Igfbp4'],
        'Erythroid Cells': ['Hba-a1', 'Hbb-bs', 'Tfrc', 'Gypa', 'Car2'],
        'Plasma Cells': ['Jchain', 'Xbp1', 'Txndc5', 'Mzb1', 'Iglc2'],
        'Monocyte Progenitors': ['Mki67', 'Top2a', 'Stmn1', 'Crip1', 'Fn1'],
    }
}